export const LOAD_SONG_LIST = 'app/SongList/LOAD_SONG_LIST';
export const LOAD_SONG_LIST_SUCCESS = 'app/SongList/LOAD_SONG_LIST_SUCCESS';
export const LOAD_SONG_LIST_ERROR = 'app/SongList/LOAD_SONG_LIST_ERROR';

export const CHANGE_SONG_LIST_PAGE = 'app/SongList/CHANGE_SONG_LIST_PAGE';
export const CHANGE_SONG_LIST_SEARCH = 'app/SongList/CHANGE_SONG_LIST_SEARCH';
export const CHANGE_SONG_LIST_FILTER = 'app/SongList/CHANGE_SONG_LIST_FILTER';
