export const LOAD_MODERATOR_STATISTIC =
  'app/UserStatistic/LOAD_MODERATOR_STATISTIC';
export const LOAD_MODERATOR_STATISTIC_SUCCESS =
  'app/UserStatistic/LOAD_MODERATOR_STATISTIC_SUCCESS';
export const LOAD_MODERATOR_STATISTIC_ERROR =
  'app/UserStatistic/LOAD_MODERATOR_STATISTIC_ERROR';
