export const LOAD_ALBUM_LIST = 'app/Song/LOAD_ALBUM_LIST';
export const LOAD_ALBUM_LIST_SUCCESS = 'app/Song/LOAD_ALBUM_LIST_SUCCESS';
export const LOAD_ALBUM_LIST_ERROR = 'app/Song/LOAD_ALBUM_LIST_ERROR';
