export const LOAD_ALBUM_LIST = 'app/AlbumList/LOAD_ALBUM_LIST';
export const LOAD_ALBUM_LIST_SUCCESS = 'app/AlbumList/LOAD_ALBUM_LIST_SUCCESS';
export const LOAD_ALBUM_LIST_ERROR = 'app/AlbumList/LOAD_ALBUM_LIST_ERROR';

export const CHANGE_ALBUM_LIST_PAGE = 'app/AlbumList/CHANGE_ALBUM_LIST_PAGE';
export const CHANGE_ALBUM_LIST_SEARCH =
  'app/AlbumList/CHANGE_ALBUM_LIST_SEARCH';
export const CHANGE_ALBUM_LIST_FILTER =
  'app/AlbumList/CHANGE_ALBUM_LIST_FILTER';
