export const LOAD_AUTHOR_LIST = 'app/AuthorList/LOAD_AUTHOR_LIST';
export const LOAD_AUTHOR_LIST_SUCCESS =
  'app/AuthorList/LOAD_AUTHOR_LIST_SUCCESS';
export const LOAD_AUTHOR_LIST_ERROR = 'app/AuthorList/LOAD_AUTHOR_LIST_ERROR';

export const CHANGE_AUTHOR_LIST_PAGE = 'app/AuthorList/CHANGE_AUTHOR_LIST_PAGE';
export const CHANGE_AUTHOR_LIST_SEARCH =
  'app/AuthorList/CHANGE_AUTHOR_LIST_SEARCH';
export const CHANGE_AUTHOR_LIST_FILTER =
  'app/AuthorList/CHANGE_AUTHOR_LIST_FILTER';
